const IOT_DATA_IDLE_STATUS = 'idle';
const IOT_DATA_LOADING_STATUS = 'loading';
const IOT_DATA_FETCHED_STATUS = 'fecthed';
const IOT_DATA_FAILED_STATUS = 'failed';

export { 
  IOT_DATA_IDLE_STATUS, 
  IOT_DATA_LOADING_STATUS, 
  IOT_DATA_FETCHED_STATUS,
  IOT_DATA_FAILED_STATUS
};